# Generated by Django 4.1.1 on 2022-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("host", "Host"),)},
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_secret",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Monsieur"), ("MME", "Madame"), ("OTH", "Autre")],
                default="",
                max_length=3,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EN", "English"),
                    ("FR", "Français"),
                    ("ES", "Español"),
                    ("DE", "Deutsch"),
                ],
                default="FR",
                max_length=2,
                verbose_name="language",
            ),
        ),
    ]
