# Generated by Django 4.1.2 on 2022-10-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_bio_user_birthdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="language",
        ),
    ]
