# Generated by Django 4.1.2 on 2022-11-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Monsieur"), ("MME", "Madame"), ("OTH", "Autre")],
                default="OTH",
                max_length=3,
                verbose_name="gender",
            ),
        ),
    ]
